CREATE TABLE Cliente (
    ClienteID INT PRIMARY KEY IDENTITY(1,1),
    DNI VARCHAR(20) NOT NULL,
    Nombre VARCHAR(100) NOT NULL,
    FechaAlta DATETIME NOT NULL DEFAULT GETDATE(),
    EstadoID INT NOT NULL
);
